### ISSUE TITLE
cannot open up notebook python file:

### ISSUE THREAD

**Issue by Tyzzzzzzzz** [mrdbourke/m1-machine-learning-test#15]
Hi I was trying to open up jupyter notebook but when I wish to create a python 3 file, it shows: 500 : Internal Server Error

(base) tyz@Yus-MacBook-Pro ~ % cd tensorflow-test
(base) tyz@Yus-MacBook-Pro tensorflow-test % conda activate ./env
(/Users/tyz/tensorflow-test/env) tyz@Yus-MacBook-Pro tensorflow-test % jupyter notebook

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                       
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 14:08:31.476 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/requests/compat.py", line 11, in <module>
        import chardet
    ModuleNotFoundError: No module named 'chardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/notebookapp.py", line 2043, in init_server_extensions
        func(self)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab/serverextension.py", line 8, in load_jupyter_server_extension
        from .labapp import LabApp
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
        from jupyterlab_server import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 5, in <module>
        from .app import LabServerApp
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab_server/app.py", line 10, in <module>
        from .handlers import LabConfig, add_handlers
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab_server/handlers.py", line 18, in <module>
        from .listings_handler import ListingsHandler, fetch_listings
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jupyterlab_server/listings_handler.py", line 8, in <module>
        import requests
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/requests/__init__.py", line 45, in <module>
        from .exceptions import RequestsDependencyWarning
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/requests/exceptions.py", line 9, in <module>
        from .compat import JSONDecodeError as CompatJSONDecodeError
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/requests/compat.py", line 13, in <module>
        import charset_normalizer as chardet
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 23, in <module>
        from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/api.py", line 10, in <module>
        from charset_normalizer.md import mess_ratio
      File "charset_normalizer/md.py", line 5, in <module>
        from charset_normalizer.utils import is_punctuation, is_symbol, unicode_range, is_accentuated, is_latin, \
    ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/constant.py)
[I 14:08:31.478 NotebookApp] Serving notebooks from local directory: /Users/tyz/tensorflow-test
[I 14:08:31.478 NotebookApp] Jupyter Notebook 6.5.3 is running at:
[I 14:08:31.478 NotebookApp] http://localhost:8888/?token=2d4f247d80681f57da70a64cd7a934027961be5d54451415
[I 14:08:31.478 NotebookApp]  or http://127.0.0.1:8888/?token=2d4f247d80681f57da70a64cd7a934027961be5d54451415
[I 14:08:31.478 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:08:31.480 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/tyz/Library/Jupyter/runtime/nbserver-8200-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=2d4f247d80681f57da70a64cd7a934027961be5d54451415
     or http://127.0.0.1:8888/?token=2d4f247d80681f57da70a64cd7a934027961be5d54451415
[E 14:08:55.131 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 28, in <module>
        import cchardet as chardet_module
    ModuleNotFoundError: No module named 'cchardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 33, in <module>
        import chardet as chardet_module
    ModuleNotFoundError: No module named 'chardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/tornado/gen.py", line 782, in run
        yielded = self.gen.send(value)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 94, in get
        self.write(self.render_template('notebook.html',
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/base/handlers.py", line 511, in render_template
        return template.render(**ns)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/page.html", line 185, in top-level template code
        {% block header %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/__init__.py", line 3, in <module>
        from . import filters, postprocessors, preprocessors, writers
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/__init__.py", line 8, in <module>
        from .markdown import *
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
        from .markdown_mistune import markdown2html_mistune
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 23, in <module>
        import bs4
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/__init__.py", line 37, in <module>
        from .builder import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/builder/__init__.py", line 9, in <module>
        from bs4.element import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/element.py", line 19, in <module>
        from bs4.formatter import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/formatter.py", line 1, in <module>
        from bs4.dammit import EntitySubstitution
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 37, in <module>
        import charset_normalizer as chardet_module
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 23, in <module>
        from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/api.py", line 10, in <module>
        from charset_normalizer.md import mess_ratio
    AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
[E 14:08:55.136 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
      "Referer": "http://localhost:8888/tree",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
    }
[E 14:08:55.136 NotebookApp] 500 GET /notebooks/Untitled.ipynb (::1) 73.710000ms referer=http://localhost:8888/tree
[E 14:12:00.708 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 28, in <module>
        import cchardet as chardet_module
    ModuleNotFoundError: No module named 'cchardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 33, in <module>
        import chardet as chardet_module
    ModuleNotFoundError: No module named 'chardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/tornado/web.py", line 1713, in _execute
        result = await result
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/tornado/gen.py", line 782, in run
        yielded = self.gen.send(value)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 94, in get
        self.write(self.render_template('notebook.html',
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/base/handlers.py", line 511, in render_template
        return template.render(**ns)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/page.html", line 185, in top-level template code
        {% block header %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/templates/notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/__init__.py", line 3, in <module>
        from . import filters, postprocessors, preprocessors, writers
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/__init__.py", line 8, in <module>
        from .markdown import *
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/markdown.py", line 13, in <module>
        from .markdown_mistune import markdown2html_mistune
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 23, in <module>
        import bs4
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/__init__.py", line 37, in <module>
        from .builder import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/builder/__init__.py", line 9, in <module>
        from bs4.element import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/element.py", line 19, in <module>
        from bs4.formatter import (
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/formatter.py", line 1, in <module>
        from bs4.dammit import EntitySubstitution
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/bs4/dammit.py", line 37, in <module>
        import charset_normalizer as chardet_module
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 23, in <module>
        from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
      File "/Users/tyz/tensorflow-test/env/lib/python3.8/site-packages/charset_normalizer/api.py", line 10, in <module>
        from charset_normalizer.md import mess_ratio
    AttributeError: partially initialized module 'charset_normalizer' has no attribute 'md__mypyc' (most likely due to a circular import)
[E 14:12:00.711 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7",
      "Referer": "http://localhost:8888/tree",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
    }
[E 14:12:00.712 NotebookApp] 500 GET /notebooks/Untitled.ipynb (::1) 16.580000ms referer=http://localhost:8888/tree

**Comment by Tyzzzzzzzz** [comment]
nvm, I reinstalled the chardet.

conda install chardet
